/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.bookingsystem.InnerPanels;

import com.mycompany.bookingsystem.Helper.Helper;
import com.mycompany.bookingsystem.Launcher;
import com.mycompany.bookingsystem.Models.Entity.Entity;
import com.mycompany.bookingsystem.Models.Entity.EntityDao;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;

/**
 *
 * @author TragicNet
 */
public class ReportsPanel extends javax.swing.JPanel {

    private final String selectQuery[] = {
            "select * from entity where status <> -1 order by name collate nocase",
            "select * from entity  where status <> -1 and type = '1' order by name collate nocase",
            "select * from entity  where status <> -1 and type = '2' order by name collate nocase",
            "select * from entity  where status <> -1 and type = '3' order by name collate nocase",
            "select * from entity  where status <> -1 and type = '4' order by name collate nocase"
    };
    
    private EntityDao entityDao;
    private List<Entity> entityList;
    private DefaultListModel<String> entityListModel;
    private int selectedEntityId;
    private JRadioButton typeButtons[];
    private JRadioButton bookingSlotButtons[];
    private JRadioButton acButtons[];
    private JRadioButton statusButtons[];
    
    /**
     * Creates new form InventoryPanel
     */
    public ReportsPanel() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        typeButtonGroup = new javax.swing.ButtonGroup();
        acButtonGroup = new javax.swing.ButtonGroup();
        bookingSlotButtonGroup = new javax.swing.ButtonGroup();
        statusButtonGroup = new javax.swing.ButtonGroup();

        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(1683, 700));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1683, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGap(0, 700, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup acButtonGroup;
    private javax.swing.ButtonGroup bookingSlotButtonGroup;
    private javax.swing.ButtonGroup statusButtonGroup;
    private javax.swing.ButtonGroup typeButtonGroup;
    // End of variables declaration//GEN-END:variables
}
