/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.bookingsystem;

import static com.mycompany.bookingsystem.Helper.Helper.setUIFont;
import com.mycompany.bookingsystem.InnerPanels.BookingPanel;
import com.mycompany.bookingsystem.InnerPanels.InventoryPanel;
import com.mycompany.bookingsystem.InnerPanels.ReportsPanel;
import com.mycompany.bookingsystem.InnerPanels.SettingsPanel;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Toolkit;
import java.util.Enumeration;
import javax.swing.AbstractButton;
import javax.swing.JFrame;
import javax.swing.UIManager;

/**
 *
 * @author TragicNet
 */
public class Launcher extends javax.swing.JFrame {
    
    private final CardLayout cardLayout;
    private final InventoryPanel inventoryPanel;
    private final BookingPanel bookingPanel;
    private final ReportsPanel reportsPanel;
    private final SettingsPanel settingsPanel;
    
    /**
     * Creates new form Launcher
     */
    public Launcher() {
        
        setUIFont (new javax.swing.plaf.FontUIResource("Dialog", Font.PLAIN, 18));
        
        initComponents();
        
//        UIManager.getLookAndFeel().getDefaults().put("defaultFont", new Font("Calibri", Font.ITALIC, 12));
        
        bookingPanel = new BookingPanel(this);
        settingsPanel = new SettingsPanel(this);
        inventoryPanel = new InventoryPanel(this);
        reportsPanel = new ReportsPanel(this);
        
        cardLayout = new CardLayout();
        mainPanel.setLayout(cardLayout);
        mainPanel.add(bookingPanel, "billing");
        mainPanel.add(inventoryPanel, "inventory");
        mainPanel.add(settingsPanel, "settings");
        mainPanel.add(reportsPanel, "reports");
        
        billingButton.doClick();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cardsButtonGroup = new javax.swing.ButtonGroup();
        containerPanel = new javax.swing.JPanel();
        topPanel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        sidePanel = new javax.swing.JPanel();
        billingButton = new javax.swing.JToggleButton();
        reportsButton = new javax.swing.JToggleButton();
        inventoryButton = new javax.swing.JToggleButton();
        settingsButton = new javax.swing.JToggleButton();
        exitButton = new javax.swing.JToggleButton();
        mainContainerPanel = new javax.swing.JPanel();
        mainPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Booking System");
        setBackground(new java.awt.Color(0, 0, 0));
        setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        setName("MainFrame"); // NOI18N
        setResizable(false);

        containerPanel.setBackground(new java.awt.Color(217, 217, 217));
        containerPanel.setLayout(new java.awt.BorderLayout());

        topPanel.setBackground(new java.awt.Color(60, 110, 113));
        topPanel.setMinimumSize(new java.awt.Dimension(396, 50));
        topPanel.setPreferredSize(new java.awt.Dimension(10, 70));
        topPanel.setLayout(new java.awt.GridBagLayout());

        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Hall Billing System");
        topPanel.add(jLabel4, new java.awt.GridBagConstraints());

        containerPanel.add(topPanel, java.awt.BorderLayout.PAGE_START);

        sidePanel.setBackground(new java.awt.Color(40, 75, 99));
        sidePanel.setPreferredSize(new java.awt.Dimension(150, 456));
        java.awt.FlowLayout flowLayout1 = new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 75, 0);
        flowLayout1.setAlignOnBaseline(true);
        sidePanel.setLayout(flowLayout1);

        billingButton.setBackground(new java.awt.Color(217, 217, 217));
        cardsButtonGroup.add(billingButton);
        billingButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        billingButton.setForeground(new java.awt.Color(255, 255, 255));
        billingButton.setText("Billing");
        billingButton.setBorder(null);
        billingButton.setBorderPainted(false);
        billingButton.setContentAreaFilled(false);
        billingButton.setFocusPainted(false);
        billingButton.setPreferredSize(new java.awt.Dimension(200, 50));
        billingButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                billingButtonActionPerformed(evt);
            }
        });
        sidePanel.add(billingButton);

        reportsButton.setBackground(new java.awt.Color(217, 217, 217));
        cardsButtonGroup.add(reportsButton);
        reportsButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        reportsButton.setForeground(new java.awt.Color(255, 255, 255));
        reportsButton.setText("Reports");
        reportsButton.setBorder(null);
        reportsButton.setBorderPainted(false);
        reportsButton.setContentAreaFilled(false);
        reportsButton.setFocusPainted(false);
        reportsButton.setPreferredSize(new java.awt.Dimension(200, 50));
        reportsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reportsButtonActionPerformed(evt);
            }
        });
        sidePanel.add(reportsButton);

        inventoryButton.setBackground(new java.awt.Color(217, 217, 217));
        cardsButtonGroup.add(inventoryButton);
        inventoryButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        inventoryButton.setForeground(new java.awt.Color(255, 255, 255));
        inventoryButton.setText("Inventory");
        inventoryButton.setBorder(null);
        inventoryButton.setBorderPainted(false);
        inventoryButton.setContentAreaFilled(false);
        inventoryButton.setFocusPainted(false);
        inventoryButton.setPreferredSize(new java.awt.Dimension(200, 50));
        inventoryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inventoryButtonActionPerformed(evt);
            }
        });
        sidePanel.add(inventoryButton);

        settingsButton.setBackground(new java.awt.Color(217, 217, 217));
        cardsButtonGroup.add(settingsButton);
        settingsButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        settingsButton.setForeground(new java.awt.Color(255, 255, 255));
        settingsButton.setText("Settings");
        settingsButton.setBorder(null);
        settingsButton.setBorderPainted(false);
        settingsButton.setContentAreaFilled(false);
        settingsButton.setFocusPainted(false);
        settingsButton.setPreferredSize(new java.awt.Dimension(200, 50));
        settingsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                settingsButtonActionPerformed(evt);
            }
        });
        sidePanel.add(settingsButton);

        exitButton.setBackground(new java.awt.Color(217, 217, 217));
        cardsButtonGroup.add(exitButton);
        exitButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        exitButton.setForeground(new java.awt.Color(255, 255, 255));
        exitButton.setText("Exit");
        exitButton.setBorder(null);
        exitButton.setBorderPainted(false);
        exitButton.setContentAreaFilled(false);
        exitButton.setFocusPainted(false);
        exitButton.setPreferredSize(new java.awt.Dimension(200, 50));
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });
        sidePanel.add(exitButton);

        containerPanel.add(sidePanel, java.awt.BorderLayout.LINE_START);

        mainContainerPanel.setBackground(new java.awt.Color(217, 217, 217));
        mainContainerPanel.setOpaque(false);
        mainContainerPanel.setLayout(new javax.swing.BoxLayout(mainContainerPanel, javax.swing.BoxLayout.X_AXIS));

        mainPanel.setBackground(new java.awt.Color(255, 255, 255));
        mainPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(40, 75, 99), 0));
        mainPanel.setOpaque(false);
        mainPanel.setPreferredSize(new java.awt.Dimension(100, 100));
        mainPanel.setLayout(new java.awt.CardLayout());
        mainContainerPanel.add(mainPanel);

        containerPanel.add(mainContainerPanel, java.awt.BorderLayout.CENTER);

        getContentPane().add(containerPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void billingButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_billingButtonActionPerformed
        selectCardButton();
//        bookingPanel.reset();
        CardLayout cl = (CardLayout)(mainPanel.getLayout());
        cl.show(mainPanel, "billing");
        bookingPanel.focusIfNew();
    }//GEN-LAST:event_billingButtonActionPerformed

    private void reportsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reportsButtonActionPerformed
        selectCardButton();
        CardLayout cl = (CardLayout)(mainPanel.getLayout());
        cl.show(mainPanel, "reports");
    }//GEN-LAST:event_reportsButtonActionPerformed

    private void inventoryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inventoryButtonActionPerformed
        selectCardButton();
//        inventoryPanel.reset();
        CardLayout cl = (CardLayout)(mainPanel.getLayout());
        cl.show(mainPanel, "inventory");
    }//GEN-LAST:event_inventoryButtonActionPerformed

    private void settingsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_settingsButtonActionPerformed
        selectCardButton();
        CardLayout cl = (CardLayout)(mainPanel.getLayout());
        cl.show(mainPanel, "settings");
    }//GEN-LAST:event_settingsButtonActionPerformed

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_exitButtonActionPerformed

    private void selectCardButton() {
        for (Enumeration<AbstractButton> buttons = cardsButtonGroup.getElements(); buttons.hasMoreElements();) {
            AbstractButton button = buttons.nextElement();

            if (button.isSelected()) {
                button.setForeground(Color.black);
                button.setOpaque(true);
            } else {
                button.setForeground(Color.white);
                button.setOpaque(false);
            }
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
            
            Font defaultFont = UIManager.getDefaults().getFont("RadioButton.font");
//            setUIFont(new FontUIResource(new Font(defaultFont.getName(), defaultFont.getStyle(), 30)));
//            UIManager.put("Label.font", new Font(defaultFont.getName(), defaultFont.getStyle(), 18));
//            UIManager.put("RadioButton.font", new Font(defaultFont.getName(), defaultFont.getStyle(), 18));
//            UIManager.put("Border.font", new Font(defaultFont.getName(), defaultFont.getStyle(), 18));
            
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Launcher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Launcher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Launcher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Launcher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                
                Launcher frame = new Launcher();
                frame.pack();
                Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
                frame.setSize(screenSize);
                frame.setPreferredSize(screenSize);
                frame.setExtendedState(JFrame.MAXIMIZED_BOTH);
                frame.setLocationRelativeTo(null);
                frame.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton billingButton;
    private javax.swing.ButtonGroup cardsButtonGroup;
    private javax.swing.JPanel containerPanel;
    private javax.swing.JToggleButton exitButton;
    private javax.swing.JToggleButton inventoryButton;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel mainContainerPanel;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JToggleButton reportsButton;
    private javax.swing.JToggleButton settingsButton;
    private javax.swing.JPanel sidePanel;
    private javax.swing.JPanel topPanel;
    // End of variables declaration//GEN-END:variables


}
